#
# NetOffice library
# AppVeyor configuration
#

version: 1.7.4.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

matrix:
  fast_finish: true     # true => immediately finish build once one of the jobs fails

platform: Any CPU
configuration:
  - Debug
  - Release

before_build:
  - nuget restore NetOffice.sln

build:
  project: NetOffice.sln
  verbosity: detailed

cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "1.7.4-pre-{build}"

test:
  assemblies:
