# NetOffice project build definition
version: 2.0.0.{build}

branches:
  only:
    - master
    - /dev.*/
  except:
    - gh-pages
    - import/*


image: Visual Studio 2017

platform: Any CPU
configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 15.0

init:
  git config --global core.autocrlf true

build:
  project: Source\NetOffice.sln
  verbosity: normal

before_build:
  - appveyor-retry nuget restore Source\NetOffice.sln
